-- Structure based on fastfetch 2.0.0+

# Display Settings
logo=arch
logo-type=builtin
logo-padding=3
logo-color=6
logo-width=34

# Module Settings
separator=": "
modules=title,separator,os,separator,host,separator,kernel,separator,uptime,separator,packages,separator,shell,separator,terminal,separator,cpu,separator,gpu,separator,memory,separator,colors

# Module Customizations
title-name=fastfetch
title-color=6

os-name=Arch Linux
os-pretty-name=Arch Linux

packages-prefix="Official: "
packages-format="{} (pacman)"
packages-color=2

shell-format="{1}"
terminal-format="{1}"

cpu-format="{1}"
gpu-format="{1}"

memory-format="{1} GB / {2} GB"
memory-percent=1
memory-used=1
memory-total=1

colors-colors=1,2,3,4,5,6,7
colors-blocks="■■■■■■■"
colors-spacing=1
